accounts/urls.py
from django.urls import path
from . import views 

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
]

articles/urls.py
from django.urls import path
from . import views 

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:article_id>/', views.comments, name='comments'),
    path('<int:article_id>/comments/', views.comment_create, name='comment_create'),
    path('<int:article_id>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_id>/like/', views.like, name='like'),
    path('explore/<tag>/',  views.index, name='tag'),
    path('search/', views.search, name='search')
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as accounts_views
from articles import views as articles_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', articles_views.index, name='root'),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    # 우리가 정의한 accounts.url 아래에
    path('accounts/', include('allauth.urls')),
    path('<str:username>/follow/', accounts_views.follow, name='follow'),
    path('<str:username>/', accounts_views.profile, name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#string을 밑에 놓는 이유는 문자열이라서 위에 다른 url로 빠지지 않고 다 string url로 빠지게 됨

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit
import hashlib

# settings.AUTH_USER_MODEL  == string
# get_user_model() == class


class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')

    @property
    def gravatar_url(self):
        return f"https://s.gravatar.com/avatar/{hashlib.md5(self.email.encode('utf-8').strip().lower()).hexdigest()}?s=170&d=mp"

articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, ResizeToFit, Thumbnail
import re

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(blank=True)
    # DB 저장 x, 호출하게 되면 잘라서 표현
    image_thumbnail = ImageSpecField(source='image',
                                      processors=[ResizeToFit(700, 700)],
                                      format='JPEG',
                                      options={'quality': 60})
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # 주로 목적어가 되는 model에 정의를 함
    liked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_articles')
    # 해쉬태그 M:N
    tags = models.ManyToManyField('Hashtag', blank=True)

    class Meta:
        ordering = ['-created_at',]

    def tag_save(self):
        tags = re.findall(r'#(\w+)\b', self.content)

        if not tags:
            return

        for t in tags:
            tag, tag_created = Hashtag.objects.get_or_create(name=t)
            self.tags.add(tag)  

class Comment(models.Model):
    content = models.CharField(max_length=200)
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add =True)
    parent = models.ForeignKey('self', related_name='replies', on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        ordering = ['created_at',]


class Hashtag(models.Model):
    name = models.CharField(max_length=100, unique=True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['username','first_name','last_name','email']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login, logout as auth_logout, get_user_model
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect, JsonResponse
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib import messages

User = get_user_model()

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            messages.add_message(request, messages.INFO, 'Welcome '+user.username +'!')
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            messages.add_message(request, messages.INFO, 'Login Successfull!')
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    auth_logout(request)
    messages.add_message(request, messages.SUCCESS, "You've been logged out.")
    return redirect('articles:index')

@login_required
def follow(request, username):
    person = get_object_or_404(User, username=username)
    user = request.user
    if user in person.followers.all():
        person.followers.remove(user)
        following = False
    else:
        person.followers.add(user)
        following = True
    context = {
        'following': following,
        'followingCount': person.followings.count(),
        'followerCount': person.followers.count(),
    }
    return JsonResponse(context)

def profile(request, username):
    #해당 유저 (username)의 정보를 보여줌
    person = get_object_or_404(User, username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)


def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context ={
        'form':form
    }
    return render(request, 'accounts/update.html', context)

@require_POST
@login_required
def delete(request):
    request.user.delete()
    messages.add_message(request, messages.ERROR, "Your account has been deleted.")
    return redirect('articles:index')

accounts/templates/accounts/follow.html
{% if request.user != article.user %}
<span class="text-primary ml-3 text-decoration-none followButtons" data-name="{{article.user.username}}" style="font-size: 0.9rem"> 
     {% if request.user not in article.user.followers.all%}
       Follow 
     {% else %}
       Following
     {% endif %}
 </span>      
{% endif %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}

{% block content %}
  <div class="mx-auto col-xl-6 col-lg-9 col-md-12">
    <h4>LOGIN</h4>
    <form action="" method="POST" class="mb-4">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div style="height: 20px"></div>
      <button class="btn btn-warning d-block text-white w-25 text-center"><strong>Login</strong></button>
    </form>

    <p class="w-100 text-center pb-2">Don't have an account? </p>
    <p><a href="{% url 'accounts:signup' %}" class="btn btn-success w-100">Sign up free!</a></p>
    <p class="w-100 text-center">or</p>
    <p><a href="{% provider_login_url 'google' %}" class="btn btn-danger w-100"><i class="fab fa-google mr-2"></i>Login with Google</a></p>
    <p><a href="{% provider_login_url 'github' %}" class="btn btn-dark w-100"><i class="fab fa-github mr-2"></i> Login with Github</a></p>
  </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load article_extras%}

{% block title%}
    {{person.username}} |
{% endblock %}

{% block content %}

<div class="d-flex justify-content-between align-items-center">
    <div class="col-md-3 col-sm-1 text-center">
        <img src="{{person.gravatar_url}}" class="rounded-circle w-75" />
        <p class="d-inline w-75" style="font-size: 2rem">{{ person.username }}</p>
    </div>
    <div class="d-flex">
        <div class="text-center d-inline px-2">
            <p class="text-center ">{{person.article_set.count}}</p>
            <p class="text-center ">Posts</p>
        </div>
        <div class="text-center d-inline px-2" data-toggle="modal" data-target="#followersModal">
            <p class="text-center followerCount">{{person.followers.count}}</p>
            <p class="text-center">Followers</p>
        </div>
        <div class="text-center d-inline px-2" data-toggle="modal" data-target="#followingModal">
            <p class="text-center followingCount">{{person.followings.count}}</p>
            <p class="text-center ">Following</p>
        </div>
    </div>
</div>


{% include '_followersmodal.html' %}
{% include '_followingmodal.html' %}

<p class="mt-3 mb-5">
{% if user.username == person.username %}
    <span class="d-block w-100 m-auto text-center">
    <a href="{% url 'accounts:update' %}" class="w-50 mr-1 btn btn-warning text-white">
        <strong>Edit Profile</strong>
    </a>
    <button class="btn btn-secondary shadow-none" href="#" data-toggle="modal" data-target="#accountDeleteModal"><i class="fa fa-trash" aria-hidden="true"></i></button>
    </span>
    {% include '_accountdelete.html'%}
{% else %}
    
    <span href="{% url 'follow' person.username %}" class="d-block w-50 m-auto btn btn-warning text-white"> 
        <strong id="followButton" data-name="{{person.username}}">
        {% if request.user in person.followers.all %}
            Following
        {% else %}
            Follow
        {% endif %}
        </strong>
    </span>
    
{% endif %}
</p>

<div class="row">
{% for article in person.article_set.all%}
  <div class="col-4 d-flex align-items-center">
    <a href="{% url 'articles:comments' article.pk %}">
        <img src="{{article.image_thumbnail.url}}" class="pb-2" width="100%"/>
    </a>
  </div>

  {% empty %}
  <div class = "w-100 text-center my-5">
    <h4>There is no post!</h4>
    <p>Upload your first gram-gram photo today.</p>
    <a class="btn btn-info text-white d-block w-25 m-auto" href="{% url 'articles:create' %}" style='font-size:22px;'><strong>Write a Post</strong> </a>
  </div>
    {% endfor %}
</div>

<script>
const followButton = document.querySelector('#followButton')
followButton.addEventListener('click', event => {
    const userName = event.target.dataset.name
    {% if user.is_authenticated %}
        axios.get(`/${userName}/follow/`)
        .then (response => {
            followingCount = document.querySelector('.followingCount').innerText = response.data.followingCount
            followerCount = document.querySelector('.followerCount').innerText = response.data.followerCount
            if (response.data.following){
                event.target.innerText = 'Following'
            }else {
                event.target.innerText = 'Follow'
            }
        })
    {% else %}
        alert('Please login!')
    {% endif %}
})
</script>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title%}
    Gram-gram Signup
{% endblock %}

{% block content %}
  <h2>SIGNUP</h2>
  <form action="" method="POST">
    {% csrf_token %}
    {%bootstrap_form form %}
    <button class="btn btn-warning">Submit</button>
  </form>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<h2 class="my-4">Edit Your Profile</h2>

<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-success mt-3 mb-4">Save the changes</button>
</form>
{% endblock  %}