articles/urls.py
from django.urls import path
from . import views 

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:article_id>/', views.comments, name='comments'),
    path('<int:article_id>/comments/', views.comment_create, name='comment_create'),
    path('<int:article_id>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_id>/like/', views.like, name='like'),
    path('explore/<tag>/',  views.index, name='tag'),
    path('search/', views.search, name='search')
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as accounts_views
from articles import views as articles_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', articles_views.index, name='root'),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    # 우리가 정의한 accounts.url 아래에
    path('accounts/', include('allauth.urls')),
    path('<str:username>/follow/', accounts_views.follow, name='follow'),
    path('<str:username>/', accounts_views.profile, name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#string을 밑에 놓는 이유는 문자열이라서 위에 다른 url로 빠지지 않고 다 string url로 빠지게 됨

articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, ResizeToFit, Thumbnail
import re

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(blank=True)
    # DB 저장 x, 호출하게 되면 잘라서 표현
    image_thumbnail = ImageSpecField(source='image',
                                      processors=[ResizeToFit(700, 700)],
                                      format='JPEG',
                                      options={'quality': 60})
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # 주로 목적어가 되는 model에 정의를 함
    liked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_articles')
    # 해쉬태그 M:N
    tags = models.ManyToManyField('Hashtag', blank=True)

    class Meta:
        ordering = ['-created_at',]

    def tag_save(self):
        tags = re.findall(r'#(\w+)\b', self.content)

        if not tags:
            return

        for t in tags:
            tag, tag_created = Hashtag.objects.get_or_create(name=t)
            self.tags.add(tag)  

class Comment(models.Model):
    content = models.CharField(max_length=200)
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add =True)
    parent = models.ForeignKey('self', related_name='replies', on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        ordering = ['created_at',]


class Hashtag(models.Model):
    name = models.CharField(max_length=100, unique=True)

articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        max_length=100,
        label='Title',
        help_text='Your title must be no more than 100 characters in length',
        widget=forms.TextInput(
            attrs={
                'class':'my_input',
                'placeholder': "What's on your mind?"
            }
        )
    )
    content = forms.CharField(
        label='Content',
        help_text='Jot down random musings and thoughts',
        widget=forms.Textarea(
            attrs={
                'row':5,
                'col':50,
                'placeholder': "You can add tags by putting pound sign (#) infront of it!"
            }
        )
    )
    class Meta:
        model = Article 
        exclude = ['created_at', 'updated_at', 'user', 'liked_users','tags',]


class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label = '',
        widget=forms.TextInput(
            attrs={
                'row':2,
                'col':10,
                'placeholder':'Add a comment...',
                'class':'form-control',
            }
        )
    )
    class Meta:
        model = Comment
        fields = ['content']

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.http import require_POST 
from django.http import HttpResponseRedirect, JsonResponse

from .models import Article, Comment
from .forms import ArticleForm, CommentForm


def index(request, tag=None):
    articles = Article.objects.prefetch_related('tags').order_by('-pk')
    keyword = count = 0
    if tag:
        articles = Article.objects.filter(tags__name__iexact=tag)
        keyword = tag
        count = Article.objects.filter(tags__name__iexact=tag).count()
    context = {
        'articles': articles,
        'keyword': keyword,
        'count': count,
    }
    return render(request, 'articles/index.html', context)

def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            article.tag_save()
            messages.add_message(request, messages.INFO, 'Your post has been successfully submitted!')
            return redirect('articles:index')
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/form.html', context)

@login_required
@require_POST
def delete(request):
    pk = request.POST.get('post_id')
    article = get_object_or_404(Article, id=pk)
    if request.user == article.user:
        article.delete()
        messages.add_message(request, messages.SUCCESS, 'Your post has been successfully deleted!')
    return redirect('articles:index')

@login_required                                                                                          
def update(request, pk):
    article = get_object_or_404(Article, id=pk)
    if request.user == article.user:
        if request.method == "POST":
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                article = form.save(commit=False)
                article.user = request.user
                article.save()
                messages.add_message(request, messages.SUCCESS, 'Your post has been successfully updated!')
                return redirect('articles:index')
        else:
            form = ArticleForm(instance=article)
        context = {
            'form': form,
            'article': article,
        }
        return render (request, 'articles/form.html', context)
    else:
        messages.warning(request, "Editting other people's post is not allowed")
        return redirect('articles:index')

# [ axios로 바꾸기 전 ]
# @login_required
# def like(request, article_id):
#     article = get_object_or_404(Article, id=article_id)
#     user = request.user
#     # ver1)
#     # if request.user in article.liked_users.all():
    
#     # ver2)
#     if article.liked_users.filter(id=user.id).exists():
#         article.liked_users.remove(user) #id 넣어도 되지만 django는 똑똑해서 객체 자체를 넣어줘도 됨
#     else:
#         article.liked_users.add(user)
#     return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

@login_required
def like(request, article_id):
    user = request.user
    article = get_object_or_404(Article, id=article_id)
    if article.liked_users.filter(id=user.id).exists():
        article.liked_users.remove(user)
        liked=False
    else:
        article.liked_users.add(user)
        liked=True
    if article.liked_users.count() > 0:
        first = article.liked_users.all()[0].username
    else:
        first = None
    
    context = {
        'liked':liked,
        'count': article.liked_users.count(),
        'first': first,
    }
    return JsonResponse(context)


def comments(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    form = CommentForm()
    context = {
        'article':article,
        'form':form,
    }
    return render(request, 'articles/comment.html', context)

@require_POST
def comment_create(request, article_id):
    if request.user.is_authenticated:
        article =  get_object_or_404(Article, id=article_id)
        form = CommentForm(request.POST)
        if form.is_valid():
            parent_obj = None
            # 부모 댓글 가져오깅
            try:
                parent_id = int(request.POST.get('parent_id'))
            except:
                parent_id = None
            if parent_id:
                parent_obj = Comment.objects.get(id=parent_id)
                # 부모 댓글 있으면,
                if parent_obj:
                    reply_comment = form.save(commit=False)
                    reply_comment.parent = parent_obj

            comment = form.save(commit=False)
            comment.user = request.user
            comment.article = article
            comment.save()
        return redirect('articles:comments', article.pk)
    else:
        messages.warning(request, 'Login first to write a comment!')
        return redirect('accounts:login')

@require_POST
def comment_delete(request, article_id, comment_id):
    if request.user.is_authenticated:
        comment = Comment.objects.get(id=comment_id)
        if comment.user == request.user:
            comment.delete()
        return redirect('articles:comments', article_id)
    else:
        messages.danger(request, 'You do not have permission to delete this comment.')
        return redirect('accounts:login')

def search(request):
    keyword = request.POST.get('keyword')
    articles = Article.objects.filter(tags__name__iexact=keyword)
    count = Article.objects.filter(tags__name__iexact=keyword).count()
    context = {
        'articles': articles,
        'keyword': keyword,
        'count': count,
    }
    return render(request, 'articles/index.html', context)

articles/templates/articles/comment.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% load article_extras %}
{% load mathfilters %}
{% block title%}
{{article.user.username}} on Gram-gram
{% endblock %}

{% block content %}


<div class="row mt-4" style="height:700px">
    <div class="col-xl-8 d-none d-sm-none d-md-none d-lg-none d-xl-block">
        <div class="d-flex align-items-center h-100">
            <img src="{{article.image_thumbnail.url}}" class="d-block m-auto pb-2" />
        </div>
    </div>
    <div class="col border p-1 position-relative">
        <div class="border-bottom d-flex justify-content-between pl-1 pt-1">
            <h5><a href="{% url 'profile' article.user.username %}" class="text-dark text-decoration-none">
                <img src="{{article.user.gravatar_url}}" class="rounded-circle mr-2" height="40" width="40" />
                <strong>{{ article.user.username }}</strong></a> 
                <span>{% include 'accounts/follow.html'%}</span>
            </h5>

            {% if user.username == article.user.username %}
            <div class="btn-group dropright">
                <button class="btn shadow-none" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <i class='fas fa-ellipsis-h text-secondary'></i>
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item text-decoration-none" href="{% url 'articles:update' article.pk %}"><strong>Edit</strong></a>
                    <button class="dropdown-item" href="#" data-toggle="modal"
                        data-target="#deleteModal"><strong>Delete</strong></button>
                </div>
            </div>
            {% endif %}
        </div>
        {% include '_deletemodal.html'%}
        <div class="border-left border-right border-bottom pl-2 pt-2" style="height: 450px; overflow-y: auto">
            <div class="mb-2 mt-1">
                <a href="{% url 'profile' article.user.username %}" class="text-dark text-decoration-none">
                <img src="{{article.user.gravatar_url}}" class="rounded-circle mr-2" height="40" width="40" />
                <h5 class="d-inline">{{article.user}}</h5>
            </a>
                <h5 class="card-title mt-2">{{article.title}}</h5>
            </div>
            <p>{{article|add_link|safe|linebreaksbr}}</p>

            {% for comment in article.comments.all %}
            {% if comment.parent == null %}
            <div class="m-0 d-block">
                <div class="d-flex justify-content-between">
                    <p class="mb-0 p-0 d-block">
                        <a href="{% url 'profile' comment.user.username %}" class="text-dark text-decoration-none">
                        <img src="{{comment.user.gravatar_url}}" class="rounded-circle" height="40" width="40" />
                        <strong>{{comment.user}}</strong>
                        </a>
                        : {{ comment.content }}
                    </p>
                    <div>
                        {% if comment.user.username == user.username %}
                        <div class="btn-group dropdown">
                            <button class="btn shadow-none" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                <i class='fas fa-ellipsis-h text-secondary'></i>
                            </button>
                            <div class="dropdown-menu">
                                <button class="dropdown-item" href="#" data-toggle="modal"
                                    data-target="#commentdeleteModal"><strong>Delete</strong></button>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
                <div class="d-block ml-4 pl-2">
                    <span class="text-secondary"
                        style="font-size: 0.8rem">{{comment.created_at|date:'Y-m-d H:i'}}</span>
                    <span class="btn text-secondary reply_toggler"
                        style="font-size: 0.8rem"><strong>Reply</strong></span>
                </div>
                {% include '_commentdelete.html'%}
                

                {% if comment.replies.count > 0 %}
                    {% include '_replies.html'%}
                {% endif %}
                <div class="reply_form" style="display:none">
                    <form action="{% url 'articles:comment_create' article.pk %}" method="POST"
                        enctype="multipart/form-data" class="d-flex">
                        {% bootstrap_form form %}
                        {% csrf_token %}
                        <input type="hidden" name="parent_id" value="{{ comment.pk }}" >
                        <input class="btn btn-primary" type="submit" value="Reply" style="height: 47px;">
                    </form>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        <div class="d-block w-100 pt-2 pl-2 position-absolute fixed-bottom fixed-right">
            <div class="d-block">
                <span>{% include 'articles/like.html'%}</span>
                <span><a href="{% url 'articles:comments' article.pk %}"><i class="far fa-comment text-secondary"
                            style='font-size:27px'></i></a></span>
            </div>
            <p data-toggle="modal" data-target="#likesModal" class="m-0"> 
                {% if article.liked_users.count >= 2 %}
                  <span id="firstLiker-{{article.pk}}">Liked by {{article.liked_users.first}}</span>
                  <span id="likeCount-{{article.pk}}">and {{article.liked_users.count|sub:1}} others</span> 
                {% elif article.liked_users.count == 1 %}
                  <span id="firstLiker-{{article.pk}}">Liked by {{article.liked_users.first}}</span>
                  <span id="likeCount-{{article.pk}}" class="d-none"></span>
                {% else %}
                  <span id="firstLiker-{{article.pk}}" class="d-none"></span> <span id="likeCount-{{article.pk}}" class="d-none"></span>
                {% endif %}
              </p>
            <p class="mt-0 text-secondary"><small>{{ article.created_at|date:'Y-m-d H:i' }}</small></p>
            <div>
                <form action="{% url 'articles:comment_create' article.pk %}" method="POST"
                    enctype="multipart/form-data" class="d-flex">
                    {% csrf_token %}
                    {% bootstrap_form form%}
                    <button class="btn btn-warning py-0" style="height: 47px;"><strong>Post</strong></button>
                </form>
            </div>
        </div>
    </div>
</div>

{% include '_likesmodal.html' %}

<script>
    $(document).ready(function () {
        $(".reply_toggler").click(function () {
            $(this).parent().parent().children(".reply_form").toggle();
        });

        $(".view_replies").click(function () {
            var count = $(this).attr('reply-count')
            console.log(count)
            $(this).parent().children('.replies').toggle();
            $(this).text($(this).text() == '----- Hide replies' ? '----- View replies (' + count + ')'  : '----- Hide replies');
        });
    });

    // like
    const likeButtons = document.querySelectorAll('.likeButtons')
    likeButtons.forEach( likeButton =>{
    
     likeButton.addEventListener('click', event => {
        const articleID =event.target.dataset.id
        {% if user.is_authenticated %}
            axios.get(`/articles/${articleID}/like/`)
            .then( response => {
                likeCount = response.data.count
                console.log('???', likeCount)
                if (likeCount == 0){
                  likeCount = document.querySelector(`#likeCount-${articleID}`).classList.add('d-none')
                  firstLiker = document.querySelector(`#firstLiker-${articleID}`).classList.add('d-none')
                }else if (likeCount == 1){
                  likeCount = document.querySelector(`#likeCount-${articleID}`).classList.add('d-none')
                  firstLiker = document.querySelector(`#firstLiker-${articleID}`)
                  firstLiker.innerText = 'Liked by ' + response.data.first
                  firstLiker.classList.remove('d-none')
                }else {
                  firstLiker = document.querySelector(`#firstLiker-${articleID}`)
                  firstLiker.innerText = 'Liked by ' + response.data.first
                  firstLiker.classList.remove('d-none')
                  likeCount = document.querySelector(`#likeCount-${articleID}`)
                  likeCount.classList.remove('d-none')
                  likeCount.innerText = ' and ' + (response.data.count -1) + ' others'
                }
    
                if (response.data.liked){
                    event.target.classList.remove('far', 'animated', 'infinite', 'bounce', 'slow', 'delay-1s')
                    event.target.classList.add('fas')
                }
                else {
                    event.target.classList.remove('fas')
                    event.target.classList.add('far', 'animated', 'infinite', 'bounce', 'slow', 'delay-1s')
    
                }
            })
        {% else %}
            alert('Please login!')
        {% endif %}
        })
    })

    // follow
    const followButtons = document.querySelectorAll('.followButtons')
    followButtons.forEach( followButton => {
        followButton.addEventListener('click', event => {
            const userName = event.target.dataset.name
            {% if user.is_authenticated %}
                axios.get(`/${userName}/follow/`)
                .then (response => {
                    if (response.data.following){
                        event.target.innerText = 'Following'
                    }else {
                        event.target.innerText = 'Follow'
                    }
                })
            {% else %}
                alert('Please login!')
            {% endif %}
        })
    })
</script>


{% endblock %}

articles/templates/articles/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title%}
    {{article.user.username}}
{% endblock %}

{% block content %}

<div class="pb-3">
{% if request.resolver_match.url_name == 'create'%}
    <h3>Write a post</h3>
{% else %}
    <h3>Edit your post</h3>
{% endif %}    

</div>

  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form%}
    <button class="btn btn-warning" id="post_create_update_btn"><strong>Submit</strong></button>
  </form>

{% endblock %}

articles/templates/articles/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% load article_extras %}
{% load mathfilters %}

{% block title%}

  {% if keyword %}
    # {{keyword}} on 
  {% endif %}

{% endblock %}
{% block content %}
  {% if keyword %}
    <p class="mt-1 text-center" style="font-size: 1.8rem">#{{keyword}}</p>
    <p class="mb-5 text-center">{{count}}
    
      {% if count >= 2 %}
        posts
      {% elif count == 1 %}
        post
      {% else %}

      {% endif %}
    
    </p>
  {% endif %}

  {% for article in articles %}
  <div class="card m-auto rounded-0 col-sm-12 col-md-9" >
  <div class="card-header d-flex justify-content-between bg-white pb-1"> 
    <h5 class="card-title">
      <a href="{% url 'profile' article.user.username %}" class="text-dark text-decoration-none"><img src="{{article.user.gravatar_url}}" class="rounded-circle mr-2" height="50" width="50"/>
        <strong>{{ article.user.username }}</strong>
      </a> 

      <span>{% include 'accounts/follow.html'%}</span>
    </h5>
    

    {% if user.username == article.user.username %}
    <div class="btn-group dropright">
      <button class="btn shadow-none" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class='fas fa-ellipsis-h text-secondary'></i>
      </button>
    <div class="dropdown-menu" >
      <a class="dropdown-item" href="{% url 'articles:update' article.pk %}"><strong>Edit</strong></a>
      <button class="dropdown-item" id="delete_btn" href="#" data-id= "{{article.pk}}" data-toggle="modal" data-target="#deleteModal"><strong>Delete</strong></button>
    </div>
    </div>
    {% endif %}
  </div>

  {% include '_deletemodal.html'%}

  <div class="card-body col-12">
    <img src="{{article.image_thumbnail.url}}" class="pb-2" width="100%"/>
  <div>
    <span>{% include 'articles/like.html'%}</span>
    <span><a href="{% url 'articles:comments' article.pk %}"><i class="far fa-comment text-secondary" style='font-size:27px'></i></a></span>
  </div>

    <p data-toggle="modal" data-target="#likesModal"> 
      {% if article.liked_users.count >= 2 %}
        <span id="firstLiker-{{article.pk}}">Liked by {{article.liked_users.first}}</span>
        <span id="likeCount-{{article.pk}}">and {{article.liked_users.count|sub:1}} others</span> 
      {% elif article.liked_users.count == 1 %}
        <span id="firstLiker-{{article.pk}}">Liked by {{article.liked_users.first}}</span>
        <span id="likeCount-{{article.pk}}" class="d-none"></span>
      {% else %}
        <span id="firstLiker-{{article.pk}}" class="d-none"></span> <span id="likeCount-{{article.pk}}" class="d-none"></span>
      {% endif %}
    </p>


    <h5 class="card-title">{{article.title}}</h5>
    <p>{{article|add_link|safe|linebreaksbr}}</p>

    {% if article.comments.count > 0 %}
    <a href="{% url 'articles:comments' article.pk %}" class="text-decoration-none text-secondary">
        <p class="mb-1"> View all {{article.comments.count}} comments</p>
    </a>

      {% for comment in article.comments.all|slice:":2" %}
      {% if comment.parent == null %}
      <div class="d-flex justify-content-between ">
        <p class="mb-0 p-0 d-block">
            <a href="{% url 'profile' comment.user.username %}" class="text-dark text-decoration-none">
            <strong>{{comment.user}}</strong>
            </a>
            : {{ comment.content }}
        </p>
        <div>
            {% if comment.user.username == user.username %}
            <div class="btn-group dropdown">
                <button class="btn shadow-none py-0" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <i class='fas fa-ellipsis-h text-secondary'></i>
                </button>
                <div class="dropdown-menu">
                    <button class="dropdown-item" href="#" data-toggle="modal"
                        data-target="#commentdeleteModal"><strong>Delete</strong></button>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
      {% endif %}
      {% endfor %}
    {% endif %}

    <p class="text-secondary"><small>{{ article.created_at|date:'Y-m-d H:i' }}</small></p>
  </div>
  </div>

  {% include '_likesmodal.html' %}

  {% empty %}
  
  
  <h3 class="text-center pt-5 mb-3">There is no post!</h3>
  <p class="text-center pb-2">Upload your first gram-gram photo today.</p>
  <a class="btn btn-warning text-white d-block w-25 m-auto" href="{% url 'articles:create' %}" style='font-size:22px;'><strong>Write a Post</strong> </a>
  
  
  {% endfor %}


<script>

// like
const likeButtons = document.querySelectorAll('.likeButtons')
 likeButtons.forEach( likeButton =>{

 likeButton.addEventListener('click', event => {
    const articleID =event.target.dataset.id
    {% if user.is_authenticated %}
        axios.get(`/articles/${articleID}/like/`)
        .then( response => {
            likeCount = response.data.count
            console.log('???', likeCount)
            if (likeCount == 0){
              likeCount = document.querySelector(`#likeCount-${articleID}`).classList.add('d-none')
              firstLiker = document.querySelector(`#firstLiker-${articleID}`).classList.add('d-none')
            }else if (likeCount == 1){
              likeCount = document.querySelector(`#likeCount-${articleID}`).classList.add('d-none')
              firstLiker = document.querySelector(`#firstLiker-${articleID}`)
              firstLiker.innerText = 'Liked by ' + response.data.first
              firstLiker.classList.remove('d-none')
            }else {
              firstLiker = document.querySelector(`#firstLiker-${articleID}`)
              firstLiker.innerText = 'Liked by ' + response.data.first
              firstLiker.classList.remove('d-none')
              likeCount = document.querySelector(`#likeCount-${articleID}`)
              likeCount.classList.remove('d-none')
              likeCount.innerText = ' and ' + (response.data.count -1) + ' others'
            }

            if (response.data.liked){
                event.target.classList.remove('far', 'animated', 'infinite', 'bounce', 'slow', 'delay-1s')
                event.target.classList.add('fas')
            }
            else {
                event.target.classList.remove('fas')
                event.target.classList.add('far', 'animated', 'infinite', 'bounce', 'slow', 'delay-1s')

            }
        })
    {% else %}
        alert('Please login!')
    {% endif %}
    })
})

// follow
const followButtons = document.querySelectorAll('.followButtons')
followButtons.forEach( followButton => {
    followButton.addEventListener('click', event => {
        const userName = event.target.dataset.name
        {% if user.is_authenticated %}
            axios.get(`/${userName}/follow/`)
            .then (response => {
                if (response.data.following){
                    event.target.innerText = 'Following'
                }else {
                    event.target.innerText = 'Follow'
                }
            })
        {% else %}
            alert('Please login!')
        {% endif %}
    })
})
  </script>


{% endblock %}

articles/templates/articles/like.html
<span class="btn pt-0 pl-0 pr-1">
    {% if user in article.liked_users.all %}
    <i class="fas fa-heart fa-lg text-danger mr-2 likeButtons"  data-id="{{article.pk}}" onmouseover="this.style.color='white'" onmouseout="this.style.color='red'"></i>
    {% else %}
    <i class="far fa-heart fa-lg text-danger mr-2 animated infinite bounce slow delay-1s likeButtons"  data-id="{{article.pk}}" onmouseover="this.style.color='white'" onmouseout="this.style.color='red'"></i>
    {% endif %}
</span>