accounts/urls.py
from django.urls import path
from . import views 

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
]

articles/urls.py
from django.urls import path
from . import views 

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:article_id>/', views.comments, name='comments'),
    path('<int:article_id>/comments/', views.comment_create, name='comment_create'),
    path('<int:article_id>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_id>/like/', views.like, name='like'),
    path('explore/<tag>/',  views.index, name='tag'),
    path('search/', views.search, name='search')
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as accounts_views
from articles import views as articles_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', articles_views.index, name='root'),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    # 우리가 정의한 accounts.url 아래에
    path('accounts/', include('allauth.urls')),
    path('<str:username>/follow/', accounts_views.follow, name='follow'),
    path('<str:username>/', accounts_views.profile, name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#string을 밑에 놓는 이유는 문자열이라서 위에 다른 url로 빠지지 않고 다 string url로 빠지게 됨

templates/_accountdelete.html
<!-- Delete Modal!! -->
<form action="{% url 'accounts:delete'%}" method="POST">
  {% csrf_token %}
<div class="modal fade" id="accountDeleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header w-100">
       <h4 class="modal-title " id="exampleModalLabel">Delete your account</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center mt-2 mb-3">
     
       <p style="font-size: 1.4rem"> Hi, {{user.username}}! <br>
        We're sorry to hear you'd like to delete your account.</p>
        When you press the button below, your photos, comments, likes, friendships and all other data will be removed permanently and will not be recoverable. <br>
        If you decide to create another Gram-gram account in the future, you cannot sign up with the same username again.<br>
      </div>
      <div class="modal-footer">
          <button type="submit" class="btn btn-danger text-white"> Delete</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
 </form>

templates/_commentdelete.html
<!-- Delete Modal!! -->
<form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method="POST">
    {% csrf_token %}
    <div class="modal fade" id="commentdeleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header w-100">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body text-center mt-2 mb-3">
                    <h4 class="modal-title mb-3" id="exampleModalLabel">Are you sure?</h4>
                    Do you really want to delete your comment? <br>
                    This process cannot be undone.
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger text-white"> Delete</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</form>

templates/_deletemodal.html
<!-- Delete Modal!! -->
<form action="{% url 'articles:delete'%}" method="POST">
  {% csrf_token %}
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header w-100">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center mt-2 mb-3">
      <h4 class="modal-title mb-3" id="exampleModalLabel">Are you sure?</h4>
        Do you really want to delete post? <br>
        This process cannot be undone.
         <input type="text" id="post_id" name="post_id" hidden></input>
      </div>
     
      <div class="modal-footer">
          <button type="submit" class="btn btn-danger text-white"> Delete</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
 </form>


<script>
$(document).on("click", "#delete_btn", function () {  
  var id = $(this).attr('data-id');   
  $("#post_id").val(id); 
})  
</script> 

templates/_followersmodal.html
<!-- followersModal -->
<div class="modal fade" id="followersModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title m-auto pl-4"  id="exampleModalLongTitle">Followers</h5>
          <button type="button" class="close mx-0 px-1 " data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {% for follower in person.followers.all %}
           <div class="d-flex justify-content-between">
            <p class="ml-1" style="font-size: 1.1rem">
              <a href="{% url 'profile' follower.username %}" class="text-decoration-none text-reset">
                <img src="{{follower.gravatar_url}}" class="rounded-circle mr-1" height="30" width="30" /> {{ follower.username }}</p>
              </a>
            <p>
              {% if request.user != follower %}
                <a href="{% url 'follow' follower.username %}" class="d-block m-auto btn btn-warning text-white"> 
                    <strong>
                    {% if request.user in follower.followers.all %}
                        Following
                    {% else %}
                        Follow
                    {% endif %}
                    </strong>
                </a>
              {% endif %}
            </p>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

templates/_followingmodal.html
<!-- followingModal -->
<div class="modal fade" id="followingModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title m-auto pl-4"  id="exampleModalLongTitle">Following</h5>
          <button type="button" class="close mx-0 px-1 " data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {% for following in person.followings.all %}
           <div class="d-flex justify-content-between">
            <p class="ml-1" style="font-size: 1.1rem">
              <a href="{% url 'profile' following.username %}" class="text-decoration-none text-reset">
                <img src="{{following.gravatar_url}}" class="rounded-circle mr-1" height="30" width="30" /> {{ following.username }}</p>
              </a>
            <p>
              {% if request.user != following %}
                <a href="{% url 'follow' following.username %}" class="d-block m-auto btn btn-warning text-white"> 
                    <strong>
                    {% if request.user in following.followers.all %}
                        Following
                    {% else %}
                        Follow
                    {% endif %}
                    </strong>
                </a>
              {% endif %}
            </p>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

templates/_likesmodal.html
<div class="modal fade" id="likesModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title m-auto pl-4"  id="exampleModalLongTitle">Likes</h5>
          <button type="button" class="close mx-0 px-1 " data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {% for liker in article.liked_users.all %}
           <div class="d-flex justify-content-between">
            <p class="ml-1" style="font-size: 1.1rem">
              <a href="{% url 'profile' liker.username %}" class="text-decoration-none text-reset">
                <img src="{{liker.gravatar_url}}" class="rounded-circle mr-1" height="30" width="30" /> {{ liker.username }}</p>
              </a>
            <p>
              {% if request.user != liker %}
                <a href="{% url 'follow' liker.username %}" class="d-block m-auto btn btn-warning text-white"> 
                    <strong>
                    {% if request.user in liker.followers.all %}
                        Following
                    {% else %}
                        Follow
                    {% endif %}
                    </strong>
                </a>
              {% endif %}
            </p>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

templates/_nav.html
<nav class="navbar navbar-expand-xl navbar-light bg-white border border-left-0 border-right-0 border-top-0 border-secondary sticky-top py-1" >
  <a class="navbar-brand" href="{% url 'root' %}"><strong class="text-dark">Gram-gram</strong></a>
  <form class="ml-5 pl-5" action="{% url 'articles:search' %}" method="POST" style="width: 400px">
  {% csrf_token %}
    <input class="form-control pl-3 ml-5 mr-sm-2" name="keyword"type="search" placeholder='Search by hashtag (#)' aria-label="Search by hashtag">
  </form>
  <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-dark "><i class="fas fa-bars" style="color:#868e96; font-size:25px;"></i></span>
  </button>
  <div class="collapse navbar-collapse " id="navbarTogglerDemo03">
    <ul class="navbar-nav ml-auto mt-2 mt-md-0 p-2">
     {% if user.is_authenticated %}

     <li><img src="{{request.user.gravatar_url}}" class="rounded-circle" height="50" width="50"/></li>
      <li class="nav-item dropdown mx-2">
        <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style='font-size:22px;'>
          Hello, {{user.username}}!
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <button class="dropdown-item"  style='font-size:22px;'><a href="{% url 'profile' user.username %}" class="text-decoration-none">Profile</a></button>
          <button class="dropdown-item"  style='font-size:22px;'><a href="{% url 'accounts:logout' %}" class="text-decoration-none text-danger">Log-out</a></button>
        </div>
      </li> 
       <li class="nav-item mx-2">
        <a class="nav-link text-dark" href="{% url 'articles:create' %}" style='font-size:22px;'>Write a Post </a>
      </li>
      {% else %}
      <li class="nav-item active mx-2">
        <a class="nav-link text-dark" href="{% url 'accounts:login' %}" style='font-size:22px;'>Log-in<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active mx-2">
        <a class="nav-link text-dark" href="{% url 'accounts:signup' %}" style='font-size:22px;'>Join<span class="sr-only">(current)</span></a>
      </li>
      {% endif %}
    </ul>
    </div>
</nav>

templates/_replies.html
<p class="view_replies text-secondary ml-4 pl-2" style="font-size: 0.8rem" reply-count = "{{comment.replies.count}}">
    ----- View replies
    ({{comment.replies.count}}) 
</p>

<div class="replies mb-2" style="display:none">
    {% for reply in comment.replies.all %}
    <div class="d-flex justify-content-between pl-4">
        <p class="mb-3 p-0 d-block">
            <img src="{{reply.user.gravatar_url}}" class="rounded-circle" height="40" width="40" />
            <strong>{{reply.user}}</strong>: {{ reply.content }}
        </p>
        <div>
            {% if reply.user.username == user.username %}
            <div class="btn-group dropdown">
                <button class="btn shadow-none" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <i class='fas fa-ellipsis-h text-secondary'></i>
                </button>
                <div class="dropdown-menu">
                    <button class="dropdown-item" href="#" data-toggle="modal"
                        data-target="#commentdeleteModal"><strong>Delete</strong></button>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>

templates/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% load static %}
{% load article_extras %}
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="google-site-verification" content="vamTaGGeGB80zUU_DqZ3utR-uSqZvPdP0YuWmhjF0co" />
  <!-- fontawesome -->
  <script src="https://kit.fontawesome.com/f9f05d10ba.js" crossorigin="anonymous"></script>
  <!-- axios -->
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
  <link rel="shortcut icon" href="../media/favicon/instagram-64.ico">
  <link rel="icon" type="image/x-icon" href="../media/favicon/instagram-64.ico" />
  <script src="https://code.jquery.com/jquery-3.5.0.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
<title>{%block title%}{% endblock %} Gram-gram</title>
    {% bootstrap_css %}
    
</head>
<body >

  {% include '_nav.html'%}
{% if messages %}

<ul class="messages p-0">
    {% for message in messages %}
        {% if message.tags %} 
          {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
            <div class="alert alert-info ">
          {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert alert-success ">
          {% elif message.level == DEFAULT_MESSAGE_LEVELS.PRIMARY %}
            <div class="alert alert-primary ">
          {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
            <div class="alert alert-warning ">

          {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger ">
          {% endif %}
        <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>{{ message }}</strong>
        </div>
        {% endif %}
    {% endfor %}
</ul>

{% else %}
{% endif %} 


  <div class="container mt-5">
  {% block content %}
  
  {% endblock %}
  </div>

{% if request.resolver_match.url_name == 'login' or request.resolver_match.url_name == 'signup'%}

{% else %}
<footer class="footer">
    <div class="footer-copyright text-center my-4 py-3 col-12">© 2020 Copyright:
      <a href="https://github.com/chloe-codes1" class="text-decoration-none"> <i class="fab fa-github ml-1"></i> chloe-codes1</a>
    </div>
</footer>
{% endif %}

{% bootstrap_javascript jquery='full'%}


</body>
</html>